"""``python -m bre.data_cli [--only NAME ...] [--raw-dir DIR] [--out-dir DIR]``: Phase 1 ``make data``.

Runs every loader in :data:`DATASETS`, writes ``data/processed/<name>.parquet`` through
:func:`bre.schema.write_events` (which validates the frame and writes the sibling
``<name>.validation.md``), and regenerates ``data/processed/README.md`` from the actual run: one
table row per dataset (rows, subjects, elicitation types, validation ok, dropped rows and why,
seconds) plus the loaders' notes. No number in the README is typed by hand. A loader that raises
is reported in the README with its error and the process exits with status 1 after the others
have run. ``--only`` restricts the run to the named datasets (the README then lists only those).
"""

from __future__ import annotations

import argparse
import platform
import subprocess
import sys
import time
import traceback
from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime, timezone
from functools import partial
from pathlib import Path
from typing import Any

import pandas as pd

from bre import __version__
from bre.loaders import PROCESSED_DIR, RAW_DIR
from bre.loaders import choices13k, cpc15, cpc18, intake_battery, order_effects, psych201
from bre.schema import SCHEMA_VERSION, ValidationReport, write_events

README_NAME = "README.md"


@dataclass(frozen=True)
class DatasetSpec:
    name: str
    loader: Callable[..., tuple[pd.DataFrame, dict[str, Any]]]
    filename: str
    catalog_entry: str


DATASETS: dict[str, DatasetSpec] = {
    "choices13k": DatasetSpec("choices13k", choices13k.load_choices13k_with_meta, "choices13k.parquet", "A"),
    "cpc15": DatasetSpec("cpc15", cpc15.load_cpc15_with_meta, "cpc15.parquet", "B"),
    "cpc18": DatasetSpec("cpc18", cpc18.load_cpc18_with_meta, "cpc18.parquet", "B"),
    **{
        f"psych201_{folder}": DatasetSpec(
            f"psych201_{folder}", partial(psych201.load_psych201_with_meta, folder=folder), psych201.processed_name(folder), "C"
        )
        for folder in psych201.FOLDERS
    },
    "order_effects": DatasetSpec("order_effects", order_effects.load_order_effects_with_meta, "order_effects.parquet", "D"),
    "intake_battery": DatasetSpec("intake_battery", intake_battery.load_intake_battery_with_meta, "intake_battery.parquet", "instrument"),
}
"""Run order of ``make data``; keys are the ``--only`` names."""


@dataclass
class RunResult:
    name: str
    filename: str
    catalog_entry: str
    seconds: float
    meta: dict[str, Any] | None = None
    report: ValidationReport | None = None
    error: str | None = None

    @property
    def ok(self) -> bool:
        return self.error is None and self.report is not None and self.report.ok


def run_dataset(spec: DatasetSpec, raw_dir: Path, out_dir: Path) -> RunResult:
    t0 = time.time()
    try:
        frame, meta = spec.loader(raw_dir)
        report = write_events(frame, out_dir / spec.filename)
        return RunResult(spec.name, spec.filename, spec.catalog_entry, time.time() - t0, meta, report)
    except Exception as exc:  # noqa: BLE001 - reported in the README, non-zero exit at the end
        err = f"{type(exc).__name__}: {exc}"
        traceback.print_exc()
        return RunResult(spec.name, spec.filename, spec.catalog_entry, time.time() - t0, None, None, err)


def _git_head() -> str:
    try:
        out = subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True, timeout=5, check=False)
        return out.stdout.strip() or "unknown"
    except (OSError, subprocess.SubprocessError):
        return "unknown"


def _dropped_text(meta: dict[str, Any] | None) -> str:
    if not meta or not meta.get("dropped"):
        return "0"
    return "; ".join(f"{n} ({why})" for why, n in meta["dropped"].items())


def render_readme(results: list[RunResult], raw_dir: Path, out_dir: Path, only: list[str] | None) -> str:
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    lines = [
        "# data/processed — generated by `python -m bre.data_cli`",
        "",
        "<!-- generated file: every number below comes from the run recorded here; do not edit by hand -->",
        "",
        f"- generated: {now}",
        f"- command: `python -m bre.data_cli{(' --only ' + ' '.join(only)) if only else ''}`",
        f"- bre {__version__}, schema {SCHEMA_VERSION}, python {platform.python_version()}, pandas {pd.__version__}, git {_git_head()}",
        f"- raw inputs: `{raw_dir}` (provenance in `data/CATALOG.md`); outputs: `{out_dir}`",
        "- every table has `is_synthetic == False`; each parquet file has a sibling `<name>.validation.md` written by `bre.schema.write_events`",
        "",
        "## Datasets",
        "",
        "| dataset | catalog | file | rows | subjects | elicitation types | validation ok | dropped rows (why) | seconds |",
        "|---|---|---|---:|---:|---|---|---|---:|",
    ]
    for r in results:
        if r.error is not None:
            lines.append(f"| {r.name} | {r.catalog_entry} | {r.filename} | – | – | – | ERROR: {r.error} | – | {r.seconds:.1f} |")
            continue
        m = r.meta or {}
        lines.append(
            f"| {r.name} | {r.catalog_entry} | {r.filename} | {m.get('n_rows', 0)} | {m.get('n_subjects', 0)} | "
            f"{', '.join(m.get('elicitation_types', [])) or '–'} | {'yes' if r.ok else 'NO'} | {_dropped_text(m)} | {r.seconds:.1f} |"
        )
    lines += ["", "## Notes from the loaders", ""]
    for r in results:
        lines.append(f"### {r.name}")
        lines.append("")
        if r.error is not None:
            lines.append(f"- loader failed: {r.error}")
        else:
            m = r.meta or {}
            lines.append(f"- raw file: `{m.get('raw_file', '?')}`" + (f", raw rows: {m['n_raw_rows']}" if "n_raw_rows" in m else ""))
            for k in ("roundtrip_fraction", "n_lines_checked", "n_participants", "n_problems", "n_files", "n_sessions_loaded", "loss_norm", "n_loss_pct_clipped", "dominance_flag", "dominance_flag_counts", "n_pairs_unverified"):
                if k in m:
                    lines.append(f"- {k}: {m[k]}")
            for note in m.get("notes", []):
                lines.append(f"- {note}")
            if m.get("skipped_files"):
                lines.append("- skipped files: " + "; ".join(m["skipped_files"]))
            if r.report is not None:
                for w in r.report.warnings:
                    lines.append(f"- validation warning: {w}")
                for e in r.report.errors:
                    lines.append(f"- validation error: {e}")
        lines.append("")
    lines += [
        "## Not loaded",
        "",
        "Catalog entries E–K (UAS, FINRA NFCS, HRS/SCF/PSID, LISS/DNB, GPS, Robintrack, benchmark papers) are",
        "INSTRUCTIONS or GATE items in `data/CATALOG.md`; nothing of theirs is in `data/raw/`, so no loader runs",
        "for them. The market series (entry M) are not decision data and are read by `bre.market`, not written here.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m bre.data_cli", description=__doc__.split("\n\n")[0])
    parser.add_argument("--only", nargs="+", metavar="NAME", help=f"dataset name(s) to run; one of {', '.join(DATASETS)}")
    parser.add_argument("--raw-dir", type=Path, default=RAW_DIR, help=f"raw data folder (default {RAW_DIR})")
    parser.add_argument("--out-dir", type=Path, default=PROCESSED_DIR, help=f"output folder (default {PROCESSED_DIR})")
    parser.add_argument("--no-readme", action="store_true", help="do not (re)write README.md")
    args = parser.parse_args(argv)

    names = list(DATASETS)
    if args.only:
        unknown = [n for n in args.only if n not in DATASETS]
        if unknown:
            parser.error(f"unknown dataset(s) {unknown}; choose from {', '.join(DATASETS)}")
        names = [n for n in names if n in set(args.only)]
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    results: list[RunResult] = []
    for name in names:
        spec = DATASETS[name]
        print(f"[{name}] loading ...", flush=True)
        r = run_dataset(spec, Path(args.raw_dir), out_dir)
        results.append(r)
        if r.error is not None:
            print(f"[{name}] FAILED: {r.error}", flush=True)
        else:
            m = r.meta or {}
            print(f"[{name}] {m.get('n_rows', 0)} rows, {m.get('n_subjects', 0)} subjects, validation {'ok' if r.ok else 'FAILED'}, dropped {_dropped_text(m)} ({r.seconds:.1f}s)", flush=True)
    if not args.no_readme:
        (out_dir / README_NAME).write_text(render_readme(results, Path(args.raw_dir), out_dir, args.only), encoding="utf-8")
        print(f"wrote {out_dir / README_NAME}")
    return 0 if all(r.ok for r in results) else 1


if __name__ == "__main__":
    sys.exit(main())
