"""BRE database package: SQLAlchemy models, engine/session helpers and seed data.

Import ``db`` with the ``bre/`` directory on ``sys.path`` (e.g. ``python -m pytest`` from ``bre/``);
the schema constants and validators come from ``bre.schema`` (installed with ``pip install -e .``
or ``src/`` on ``sys.path``), so the parquet side and the SQLite side share one rule set.
"""

from db.models import (
    BOOL_COLUMNS,
    COVARIATE_KEYS,
    ELICITATION_TYPES,
    JSON_COLUMNS,
    LIST_COLUMNS,
    NULLABLE_COLUMNS,
    OUTCOME_BEHAVIOR_REQUIRED_KEYS,
    SCHEMA_COLUMNS,
    UNIQUE_KEY,
    AuditLog,
    Base,
    Client,
    Intervention,
    InterventionLog,
    ModelRegistry,
    PredictionLog,
    Response,
)
from db.seed import INTERVENTIONS, seed_interventions, validate_transform
from db.session import (
    DEFAULT_DB_URL,
    ENV_DB_URL,
    SyntheticPolicyError,
    absolute_sqlite_url,
    default_engine,
    delete_client,
    export_client,
    frame_to_responses,
    get_engine,
    init_db,
    resolve_db_url,
    responses_to_frame,
    session_scope,
    write_audit,
)

__all__ = [
    "AuditLog",
    "BOOL_COLUMNS",
    "Base",
    "COVARIATE_KEYS",
    "Client",
    "DEFAULT_DB_URL",
    "ELICITATION_TYPES",
    "ENV_DB_URL",
    "INTERVENTIONS",
    "Intervention",
    "InterventionLog",
    "JSON_COLUMNS",
    "LIST_COLUMNS",
    "ModelRegistry",
    "NULLABLE_COLUMNS",
    "OUTCOME_BEHAVIOR_REQUIRED_KEYS",
    "PredictionLog",
    "Response",
    "SCHEMA_COLUMNS",
    "SyntheticPolicyError",
    "UNIQUE_KEY",
    "absolute_sqlite_url",
    "default_engine",
    "delete_client",
    "export_client",
    "frame_to_responses",
    "get_engine",
    "init_db",
    "resolve_db_url",
    "responses_to_frame",
    "seed_interventions",
    "session_scope",
    "validate_transform",
    "write_audit",
]
